package csivit.rakshith.lasertag;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JDialog;
import javax.swing.JFrame;

/**
 *
 * @author rakshith
 */
public class CreateTeamFrame extends javax.swing.JFrame {

    private final Player firstPlayer;
    private final DefaultComboBoxModel model1;
    private final DefaultComboBoxModel model2;
    private final DefaultComboBoxModel model3;
    private final DefaultComboBoxModel model4;
    private final DefaultComboBoxModel model5;
    
    public CreateTeamFrame(Player defaultPlayer) {
        initComponents();
        firstPlayer = defaultPlayer;
        model1 = (DefaultComboBoxModel) jComboBox1.getModel();
        model2 = (DefaultComboBoxModel) jComboBox2.getModel();
        model3 = (DefaultComboBoxModel) jComboBox3.getModel();
        model4 = (DefaultComboBoxModel) jComboBox4.getModel();
        model5 = (DefaultComboBoxModel) jComboBox5.getModel();
        
        model1.addElement(defaultPlayer.getRegistrationNumber() + " - " + defaultPlayer.getName());
        model2.addElement("None");
        model3.addElement("None");
        model4.addElement("None");
        model5.addElement("None");
        for(Player player : Data.UnassignedPlayers) {
            model2.addElement(player.getRegistrationNumber() + " - " + player.getName());
            model3.addElement(player.getRegistrationNumber() + " - " + player.getName());
            model4.addElement(player.getRegistrationNumber() + " - " + player.getName());
            model5.addElement(player.getRegistrationNumber() + " - " + player.getName());
        }
    }
    
    protected void openForm(JFrame jFrame) {
        JDialog frame = new JDialog(this, jFrame.getTitle(), true);
        frame.getContentPane().add(jFrame.getContentPane());
        frame.pack();
        frame.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBox1.setModel(new DefaultComboBoxModel<String>());
        jComboBox1.setEnabled(false);

        jComboBox2.setModel(new DefaultComboBoxModel<String>());

        jComboBox3.setModel(new DefaultComboBoxModel<String>());

        jComboBox4.setModel(new DefaultComboBoxModel<String>());

        jComboBox5.setModel(new DefaultComboBoxModel<String>());

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox5, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(170, 170, 170))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Save
        Team team = new Team();
        team.getPlayers()[0] = firstPlayer;
        if(jComboBox2.getSelectedIndex() != 0) {
            Player player = Data.UnassignedPlayers.get(jComboBox2.getSelectedIndex() - 1);
            team.getPlayers()[1] = player;
        }
        if(jComboBox3.getSelectedIndex() != 0) {
            Player player = Data.UnassignedPlayers.get(jComboBox3.getSelectedIndex() - 1);
            team.getPlayers()[2] = player;
        }
        if(jComboBox4.getSelectedIndex() != 0) {
            Player player = Data.UnassignedPlayers.get(jComboBox4.getSelectedIndex() - 1);
            team.getPlayers()[3] = player;
        }
        if(jComboBox5.getSelectedIndex() != 0) {
            Player player = Data.UnassignedPlayers.get(jComboBox5.getSelectedIndex() - 1);
            team.getPlayers()[4] = player;
        }
        for(Player player : team.getPlayers()) {
            if(player != null) {
                Data.UnassignedPlayers.remove(player);
            }
        }
        Data.AllTeams.add(team);
        Data.UnassignedTeams.add(team);
        team.setTeamNumber(Data.AllTeams.size());
        getContentPane().setVisible(false);
        Data.save();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
