/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package csivit.rakshith.lasertag;

import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JDialog;
import javax.swing.JFrame;

/**
 *
 * @author rakshith
 */
public class ViewTeamsFrame extends javax.swing.JFrame {
    
    private final DefaultComboBoxModel model1;
    private final DefaultComboBoxModel model2;
    private final DefaultComboBoxModel model3;
    private final DefaultComboBoxModel model4;
    private final DefaultComboBoxModel model5;
    private final List<Team> teams;
    
    public ViewTeamsFrame(List<Team> teams) {
        initComponents();
        this.teams = teams;
        DefaultListModel dlm = new DefaultListModel();
        for(int i = 0; i < teams.size(); i++) {
            if(teams.get(i) != null)
                dlm.addElement("Team " + teams.get(i).getTeamNumber());
        }
        jList1.setModel(dlm);
        
        model1 = (DefaultComboBoxModel) jComboBox1.getModel();
        model2 = (DefaultComboBoxModel) jComboBox2.getModel();
        model3 = (DefaultComboBoxModel) jComboBox3.getModel();
        model4 = (DefaultComboBoxModel) jComboBox4.getModel();
        model5 = (DefaultComboBoxModel) jComboBox5.getModel();
        
        model1.addElement("None");
        model2.addElement("None");
        model3.addElement("None");
        model4.addElement("None");
        model5.addElement("None");
    }
    
    protected void openForm(JFrame jFrame) {
        JDialog frame = new JDialog(this, jFrame.getTitle(), true);
        frame.getContentPane().add(jFrame.getContentPane());
        frame.pack();
        frame.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("Save Team");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox5, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 116, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jLabel1)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        // list selection changed
        if(jList1.getSelectedIndex() >= 0) {
            Team team = teams.get(jList1.getSelectedIndex());
            model1.removeAllElements();
            model2.removeAllElements();
            model3.removeAllElements();
            model4.removeAllElements();
            model5.removeAllElements();
            
            model1.addElement("None");
            model2.addElement("None");
            model3.addElement("None");
            model4.addElement("None");
            model5.addElement("None");
            
            if(team.getPlayers()[0] != null) {
                model1.addElement(team.getPlayers()[0]);
            }
            if(team.getPlayers()[1] != null) {
                model2.addElement(team.getPlayers()[1]);
            }
            if(team.getPlayers()[2] != null) {
                model3.addElement(team.getPlayers()[2]);
            }
            if(team.getPlayers()[3] != null) {
                model4.addElement(team.getPlayers()[3]);
            }
            if(team.getPlayers()[4] != null) {
                model5.addElement(team.getPlayers()[4]);
            }
            for(Player player : Data.UnassignedPlayers) {
                model1.addElement(player);
                model2.addElement(player);
                model3.addElement(player);
                model4.addElement(player);
                model5.addElement(player);
            }
            
            jComboBox1.setSelectedIndex(0);
            jComboBox2.setSelectedIndex(0);
            jComboBox3.setSelectedIndex(0);
            jComboBox4.setSelectedIndex(0);
            jComboBox5.setSelectedIndex(0);
            
            if(team.getPlayers()[0] != null) {
                jComboBox1.setSelectedIndex(1);
            }
            if(team.getPlayers()[1] != null) {
                jComboBox2.setSelectedIndex(1);
            }
            if(team.getPlayers()[2] != null) {
                jComboBox3.setSelectedIndex(1);
            }
            if(team.getPlayers()[3] != null) {
                jComboBox4.setSelectedIndex(1);
            }
            if(team.getPlayers()[4] != null) {
                jComboBox5.setSelectedIndex(1);
            }
        }
        jLabel1.setText("");
    }//GEN-LAST:event_jList1ValueChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Save team
        if(jList1.getSelectedIndex() >= 0) {
            Team team = teams.get(jList1.getSelectedIndex());
            for(Player player : team.getPlayers()) {
                if(player != null)
                    Data.UnassignedPlayers.add(player);
            }
            if(jComboBox1.getSelectedIndex() == 0) {
                team.getPlayers()[0] = null;
            } else if(jComboBox1.getSelectedIndex() > 1) {
                team.getPlayers()[0] = Data.UnassignedPlayers.get(jComboBox1.getSelectedIndex() - 2);
            }
            if(jComboBox2.getSelectedIndex() == 0) {
                team.getPlayers()[1] = null;
            } else if(jComboBox2.getSelectedIndex() > 1) {
                team.getPlayers()[1] = Data.UnassignedPlayers.get(jComboBox2.getSelectedIndex() - 2);
            }
            if(jComboBox3.getSelectedIndex() == 0) {
                team.getPlayers()[2] = null;
            } else if(jComboBox3.getSelectedIndex() > 1) {
                team.getPlayers()[2] = Data.UnassignedPlayers.get(jComboBox3.getSelectedIndex() - 2);
            }
            if(jComboBox4.getSelectedIndex() == 0) {
                team.getPlayers()[3] = null;
            } else if(jComboBox4.getSelectedIndex() > 1) {
                team.getPlayers()[3] = Data.UnassignedPlayers.get(jComboBox4.getSelectedIndex() - 2);
            }
            if(jComboBox5.getSelectedIndex() == 0) {
                team.getPlayers()[4] = null;
            } else if(jComboBox5.getSelectedIndex() > 1) {
                team.getPlayers()[4] = Data.UnassignedPlayers.get(jComboBox5.getSelectedIndex() - 2);
            }
            for(Player player : team.getPlayers()) {
                if(player != null)
                    Data.UnassignedPlayers.remove(player);
            }
            Data.save();
            jLabel1.setText("Data saved.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
